---
galaxy_info:
  author: Andrew Rothstein
  description: iperf service
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 23
    - name: Ubuntu
      version:
        - xenial

  galaxy_tags:
    - development

dependencies: []
  
