---

#- name: template
#  ios_template:
#    username: "{{ username }}"
#    password: "{{ password }}"
#    host: "{{ ansible_ssh_host }}"
#    src: "demorouter.j2"
#  register: template

- name: router config
  ios_config:
    username: "{{ username }}"
    password: "{{ password }}"
    host: "{{ ansible_ssh_host }}"
    src: "demorouter.j2"
  register: template
  
- debug: var=template
