---
- name: ensure demorouter configuration exists
  ios_template:
    src: demorouter.j2
    username: "{{ username }}"
    password: "{{ password }}"
    host: "{{ ansible_ssh_host }}"
#  notify:
#    - write config