---
  - name: Deploy Dimension Data infrastructure  
    hosts: localhost
    vars:
      root_password: P$$ssWwrrdGoDd!
    vars_files:
      - /root/caas_credentials.yml
    tasks:
      - name: Check credentials (optionnal Step)
        caas_credentials:
          username: "{{caas_credentials.username}}"
          password: "{{caas_credentials.password}}"
          apiurl: "{{caas_credentials.apiurl}}"
          datacenter: "{{caas_credentials.datacenter}}" 
#        register: caas_credentials
#      - name: print debug
#        debug: var=caas_credentials
      - name: Deploy my Nework Domain
        caas_networkdomain:
          caas_credentials: "{{ caas_credentials }}"
          name: ansible.CaaS_Sandbox
          type: ADVANCED
        register: caas_networkdomain
