---
- name: install...
  become: yes
  become_user: root
  package: name=iperf state=present

- name: add iperf user...
  become: yes
  become_user: root
  user: name=iperf shell=/sbin/nologin
  
- name: install systemd unit...
  become: yes
  become_user: root
  with_items:
    - etc/systemd/system/iperf.service
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644

- name: launch service...
  become: yes
  become_user: root
  service: name=iperf state=started enabled=yes
  
