---
- hosts: csr
  gather_facts: no
  connection: local

  tasks: 
  - name: change_hostname
    ios_template:
      username: "{{ lookup('env','CSR_USER') }}"
      password: "{{ lookup('env','CSR_PASS') }}"
      host: "{{ ansible_ssh_host }}"
      src: demorouter.j2
    register: template

  - debug: var=template
