---
- hosts: csr
  gather_facts: no
  connection: local

  tasks: 
  - name: change_hostname
    ios_template:
      src: demorouter.j2
      username: "{{ username }}"
      password: "{{ password }}"
      host: "{{ ansible_ssh_host }}"
    register: template

  - debug: var=template
